# Generated by Django 4.1.5 on 2024-09-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='core/static/img/event_photos/default.jpg', null=True, upload_to='core/static/img/event_photos'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='core/static/documents'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tickets', models.PositiveIntegerField()),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.event')),
            ],
        ),
    ]
