# Generated by Django 4.1.5 on 2024-09-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_requires_reservation_alter_event_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
